name: Extract Assets.car
on: [workflow_dispatch]

jobs:
  extract:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check file
        run: |
          if [ ! -f "Assets.car" ]; then
            echo "File Assets.car not found!"
            exit 1
          fi

      - name: Install Tool
        run: |
          git clone https://github.com
          cd carutil
          cargo build --release
          echo "$(pwd)/target/release" >> $GITHUB_PATH

      - name: Extract
        run: |
          mkdir -p extracted_images
          ./carutil/target/release/carutil extract Assets.car --output-path ./extracted_images

      - name: Zip Files
        run: |
          zip -r images.zip extracted_images/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-extracted-images
          path: images.zip
